# Generated by Django 6.0.5 on 2026-05-15 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('preferred_date', models.DateField()),
                ('preferred_slot', models.CharField(choices=[('morning', 'Matin (8h-12h)'), ('afternoon', 'Après-midi (12h-17h)'), ('evening', 'Soir (17h-20h)')], max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Demandé'), ('assigned', 'Assigné'), ('in_transit', 'En transit'), ('arrived', 'Arrivé'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='requested', max_length=20)),
                ('status_history', models.JSONField(default=list)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('collector_notes', models.TextField(blank=True)),
                ('completion_photo', models.ImageField(blank=True, null=True, upload_to='pickups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='waste.wastelisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickup_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
