# Generated by Django 6.0.5 on 2026-05-29 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_location', to='collections.pickuprequest')),
            ],
            options={
                'db_table': 'collector_locations',
            },
        ),
    ]
