# Generated by Django 6.0.5 on 2026-05-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EcoCycle Haiti', max_length=100, verbose_name='Nom du site')),
                ('tagline', models.CharField(default='Recyclez, Gagnez, Impactez', max_length=200, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, help_text='PNG transparent, 200×60 px min', null=True, upload_to='site/logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='ICO ou PNG 32×32 px', null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('hero_badge', models.CharField(blank=True, default='🇭🇹 Pionnier du Recyclage en Haïti', max_length=100, verbose_name='Texte badge hero')),
                ('hero_title_1', models.CharField(blank=True, default='Transformez Vos Déchets', max_length=200, verbose_name='Hero — titre ligne 1')),
                ('hero_title_2', models.CharField(blank=True, default='En Trésor', max_length=200, verbose_name='Hero — titre ligne 2')),
                ('hero_subtitle', models.TextField(blank=True, default="Achetez et vendez des matériaux recyclables via des enchères sécurisées. Rejoignez l'économie circulaire d'Haïti — propulsé par l'IA.", verbose_name='Hero — sous-titre')),
                ('contact_email', models.EmailField(blank=True, default='info@ecocycle.ht', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, help_text='+509 XXXX-XXXX', max_length=30, verbose_name='WhatsApp')),
                ('address', models.TextField(blank=True, verbose_name='Adresse physique')),
                ('hours', models.CharField(blank=True, help_text='Ex: Lun–Ven 8h–17h', max_length=200, verbose_name='Horaires')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('android_apk_url', models.URLField(blank=True, verbose_name='Google Play URL')),
                ('ios_store_url', models.URLField(blank=True, verbose_name='App Store URL')),
                ('android_direct_apk', models.FileField(blank=True, help_text='Fichier .apk à télécharger directement', null=True, upload_to='android/', verbose_name='APK direct (.apk)')),
                ('meta_description', models.TextField(blank=True, help_text='160 caractères max', verbose_name='Meta description (SEO)')),
                ('google_analytics_id', models.CharField(blank=True, help_text='G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('copyright_text', models.CharField(blank=True, default='EcoCycle Haiti © 2026. Tous droits réservés.', max_length=300, verbose_name='Texte copyright')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Message de maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='♻️', max_length=10, verbose_name='Icône (emoji)')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='Étiquette (ex: Intelligence artificielle)')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('cta_text', models.CharField(blank=True, default='En savoir plus →', max_length=60, verbose_name='Texte du lien')),
                ('cta_url', models.CharField(blank=True, help_text='URL relative ou absolue', max_length=255, verbose_name='URL du lien')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': "Slides (page d'accueil)",
                'ordering': ['ordre'],
            },
        ),
    ]
