# Generated by Django 6.0.5 on 2026-05-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_site_configuration_and_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideritem',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='tag',
        ),
        migrations.AddField(
            model_name='slideritem',
            name='btn_text',
            field=models.CharField(blank=True, help_text='Laisser vide pour masquer le bouton', max_length=60, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='btn_url',
            field=models.CharField(blank=True, help_text='URL relative (/marketplace/) ou absolue', max_length=255, verbose_name='Lien du bouton'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommandé : 1600 × 700 px, format JPG/PNG', null=True, upload_to='slider/', verbose_name='Image de fond'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Sous-titre / description'),
        ),
    ]
