# Generated by Django 6.0.5 on 2026-05-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slider_image_based'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='android_apk_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='ios_store_url',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ios_direct_ipa',
            field=models.FileField(blank=True, null=True, upload_to='ios/', verbose_name='IPA iOS (.ipa)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='android_direct_apk',
            field=models.FileField(blank=True, null=True, upload_to='android/', verbose_name='APK Android (.apk)'),
        ),
    ]
