# Generated by Django 6.0.5 on 2026-05-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_title', models.CharField(max_length=300)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('angle', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('generated_content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('estimated_read_time', models.PositiveIntegerField(default=5)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('published', 'Publié')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation', to='blog.post')),
            ],
            options={
                'db_table': 'blog_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
