# Generated by Django 6.0.5 on 2026-05-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_course_price_enrollment_payment_status'),
        ('marketplace', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_created_94cd0f_idx',
            old_name='pay_tx_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_status_137fde_idx',
            old_name='pay_tx_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_transac_9fc987_idx',
            old_name='pay_tx_number_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_externa_a7becb_idx',
            old_name='pay_tx_ext_id_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='academy.enrollment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='marketplace.order'),
        ),
    ]
