# Generated by Django 6.0.5 on 2026-05-15 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('base_price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Waste Categories',
                'db_table': 'waste_categories',
            },
        ),
        migrations.CreateModel(
            name='WasteListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Poids estimé en kg', max_digits=8)),
                ('photo', models.ImageField(upload_to='waste_photos/')),
                ('photo_url', models.URLField(blank=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('ai_estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('sold', 'Vendu'), ('collected', 'Collecté'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='waste.wastecategory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waste_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WastePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='waste_photos/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='waste.wastelisting')),
            ],
            options={
                'db_table': 'waste_photos',
                'ordering': ['order'],
            },
        ),
    ]
