# Generated by Django 6.0.5 on 2026-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_lesson_pdf_display_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Gratuit'), ('pending', 'En attente de paiement'), ('paid', 'Payé')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='academy/pdfs/', verbose_name='PDF de la leçon'),
        ),
    ]
