# Generated by Django 6.0.5 on 2026-05-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_course_price_enrollment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='auto_advance_delay',
            field=models.PositiveIntegerField(default=0, help_text='Secondes avant de passer automatiquement à la leçon suivante (0 = désactivé)'),
        ),
    ]
