# Generated by Django 6.0.5 on 2026-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_course_auto_advance_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_reading_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
