# Generated by Django 6.0.5 on 2026-05-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_lesson_pdf_reading_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('youtube_videos', models.JSONField(default=list)),
                ('suggested_lessons', models.JSONField(default=list)),
                ('pdf_content', models.TextField(blank=True)),
                ('quiz_questions', models.JSONField(default=list)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('category_slug', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('published', 'Publié')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation', to='academy.course')),
            ],
            options={
                'db_table': 'course_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
