# Generated by Django 6.0.5 on 2026-05-29 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_reset_stuck_course_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_content',
            field=models.TextField(blank=True, help_text="Contenu Markdown complet du cours (généré par l'IA ou saisi manuellement)"),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('options', models.JSONField(default=list, help_text='Liste de 4 choix de réponse')),
                ('correct_answer', models.PositiveSmallIntegerField(default=0, help_text='Index (0-3) de la bonne réponse dans options')),
                ('explanation', models.TextField(blank=True, help_text='Explication de la bonne réponse')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='academy.course')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['order'],
            },
        ),
    ]
