# Generated by Django 6.0.5 on 2026-05-15 01:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_slug', models.CharField(blank=True, max_length=50)),
                ('kg_recycled', models.DecimalField(decimal_places=2, max_digits=8)),
                ('co2_saved_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('economic_value_htg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='marketplace.order')),
                ('pickup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='collections.pickuprequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'impact_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserImpactSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kg_recycled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_co2_saved_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_economic_value_htg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('community_rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_impact_summaries',
            },
        ),
    ]
