# Generated by Django 6.0.5 on 2026-05-15 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('listing_approved', 'Listing approuvé'), ('listing_rejected', 'Listing rejeté'), ('new_bid', 'Nouvelle enchère'), ('auction_won', 'Enchère gagnée'), ('auction_lost', 'Enchère perdue'), ('auction_closed', 'Enchère clôturée'), ('order_created', 'Commande créée'), ('pickup_assigned', 'Ramassage assigné'), ('pickup_status', 'Statut ramassage'), ('pickup_completed', 'Ramassage complété'), ('new_listing_admin', 'Nouveau listing (admin)'), ('system', 'Système')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
